<a href="https://colab.research.google.com/github/adnanmohit/Career_Exploration/blob/main/Day2_NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
### creating array using numpy
arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2 = np.array([11,12,13,14,15])
print(arr2)

[1 2 3 4 5]
[11 12 13 14 15]


In [ ]:
##mini task
marks = np.array([78,89,65,87,96])
print(marks)

[78 89 65 87 96]


In [ ]:
marks = np.array([[78,89,76],[87,75,86]])
print(marks)

[[78 89 76]
 [87 75 86]]


In [ ]:
###array properties
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data type:", marks.dtype)

Shape: (2, 3)
Size: 6
Data type: int64


In [ ]:
print("Shape:", arr2.shape)
print("Size:",arr2.size)
print("Data type:",arr2.dtype)

Shape: (5,)
Size: 5
Data type: int64


In [ ]:
cgpa = np.array([3.76,3.45,4.00])
print(cgpa)

[3.76 3.45 4.  ]


In [ ]:
print("Shape:", cgpa.shape)
print("Size", cgpa.size)
print("Data type", cgpa.dtype)

Shape: (3,)
Size 3
Data type float64


In [13]:
a = np.array([2,6,7])
b = np.array([5,8,3])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 7 14 10]
[-3 -2  4]
[10 48 21]
[0.4        0.75       2.33333333]


In [15]:
###mini task (create 2 array of marks from 2 exam and calculate their average using numpy )

x = np.array([70,86,93])
y =np.array([86,56,77])

##print("Average marks: ",x+y/2)
print("Average marks:", (x+y)/2)

Average marks: [78. 71. 85.]


In [31]:
arr = np.array([10, 20, 30, 40, 50])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.max(arr))
print(np.min(arr))

##mini task (Useful numpy operation)
np.random.seed(0)
array= np.random.randint(1, 100, 10)
print(np.mean(array))
print(np.min(array))
print(np.max(array))

30.0
30.0
14.142135623730951
50
10
53.5
10
88


In [32]:
##bonus task ( try doing matrix multiplications)

a= np.array([8,9,2])
b= np.array([5,4,7])

print(np.dot(a,b))

90
